apiVersion: v1
kind: Service
metadata:
  name: node-svc
  namespace: aks-demo
  labels:
    app: node-app
spec:
  type: LoadBalancer
  ports:
   - port: 3000
     targetPort: 3000
  selector:
     app: node-app

