apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: mysql-keyvault-secrets
  namespace: default
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: ""  # Set your user-assigned identity ID if applicable
    keyvaultName: "kv-akstest-01"
    cloudName: "AzurePublicCloud"
    objects: |
      array:
        - objectName: mysql-database
          objectType: secret
        - objectName: mysql-username
          objectType: secret
        - objectName: mysql-password
          objectType: secret
    tenantId: "e7e0c6c6-88ae-4a99-8404-3da70982c615"
  secretObjects:
    - secretName: mysql-secret
      type: Opaque
      data:
        - objectName: mysql-database
          key: mysql-database
        - objectName: mysql-username
          key: mysql-user
        - objectName: mysql-password
          key: mysql-password

