apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: mongo-keyvault-secrets
  namespace: default
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: ""
    keyvaultName: "kv-akstest-01"
    cloudName: "AzurePublicCloud"
    objects: |
      array:
        - objectName: MongoDB-Username
          objectType: secret
        - objectName: MongoDB-Password
          objectType: secret
        - objectName: MongoExpress-Username
          objectType: secret
        - objectName: MongoExpress-Password
          objectType: secret
    tenantId: "e7e0c6c6-88ae-4a99-8404-3da70982c615"  #KeyVault Directory Id
  secretObjects:
    - secretName: mongo-secrets
      type: Opaque
      data:
        - objectName: MongoDB-Username
          key: mongo-user
        - objectName: MongoDB-Password
          key: mongo-password
        - objectName: MongoExpress-Username
          key: express-user
        - objectName: MongoExpress-Password
          key: express-password
